# Generated by Django 3.1.1 on 2020-09-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_auto_20200923_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='isDone',
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.CharField(default=550, max_length=550),
            preserve_default=False,
        ),
    ]
